### ISSUE TITLE
No such Device

### ISSUE THREAD

**Issue by Herobr1ne** [GuiTeK/TS3Tunnel#1]
Hello, I have problems with the correct Installation. Can you help me?
(Debian 9)
Failed to open device  No such device exists (SIOCGIFHWADDR: No such device)

**Comment by Herobr1ne** [comment]
And could you perhaps send me the finished compiled client version? Can't get along with Visual Studio.

**Comment by sulimanzeen** [comment]
i already got the client version but i got the same problem in linux server

**Comment by sulimanzeen** [comment]
Issue solved I got it

**Comment by Herobr1ne** [comment]
Solved
