### ISSUE TITLE
Failed To Open Device

### ISSUE THREAD

**Issue by sulimanzeen** [GuiTeK/TS3Tunnel#2]
Hello,
 I have got the client version and turn it on successfully in my pc, but the problem is in the linux server. when i do this command.
./TS3TunnelServer khms 9987 123 42317

it give me error 1 with this message: Failed to open device khms.
i am pretty sure that the files has 777 permission

but actually what should I write instead of khms..... is it the teamspeak instance name, is ts3_inet_name the same as Teamspeak Server Name ?

I have the client version and works fine but, if I just got this command working. it would work fine...

I will be waiting for your replay

Kind regards 
SulimanZeen

**Comment by sulimanzeen** [comment]
Issue solved thanks, I have the program working well

**Comment by Catzy44** [comment]
> 
> 
> Hello,
> I have got the client version and turn it on successfully in my pc, but the problem is in the linux server. when i do this command.
> ./TS3TunnelServer khms 9987 123 42317
> 
> it give me error 1 with this message: Failed to open device khms.
> i am pretty sure that the files has 777 permission
> 
> but actually what should I write instead of khms..... is it the teamspeak instance name, is ts3_inet_name the same as Teamspeak Server Name ?
> 
> I have the client version and works fine but, if I just got this command working. it would work fine...
> 
> I will be waiting for your replay
> 
> Kind regards
> SulimanZeen

How have u solved this? Could u tell me what is "TS3_INET_NAME"?

**Comment by Catzy44** [comment]
Okay, solved, its server network interface name, in example "enp0s25".

**Comment by Herobr1ne** [comment]
Hey, can you send me the client? Server worked but not the client.

**Comment by kalek3** [comment]
> Hey, can you send me the client? Server worked but not the client.

+1

**Comment by sulimanzeen** [comment]
after gaining access to this application I have seen how dangerous this application to the Teamspeak community. which may lead people to spy on you without your knowledge. Consequently, I won't be helping anyone regarding this application. If anyone needs help on anything else then I would be happy to help. Thanks for understanding.
